In [1]:
import numpy as np

In [35]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [39]:
array=np.array([1,2,3,4,5,6])
len(array)

6

In [41]:
array=array.reshape(2,3)
array

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
array.shape

(2, 3)

In [23]:
#start,end,gap
np.arange(2,7),np.arange(3,9,2)

(array([2, 3, 4, 5, 6]), array([3, 5, 7]))

In [34]:
array=np.arange(1,20,1)
array#.reshape(4,5)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
np.tile(4,(2,5))

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [64]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [15]:
#set random variable
np.random.seed(3)

In [14]:
#start,end,shape
np.random.randint(2,5,(2,3))

array([[3, 3, 4],
       [3, 4, 2]])

In [27]:
#limit from zero,shape
np.random.choice(10,(2,3))

array([[4, 7, 8],
       [1, 6, 2]])

### Float numbers

In [13]:
#0 to 1 values shape random
np.random.rand(2,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309]])

In [7]:
#start,end,array shape
np.random.uniform(2,6,(2,4))

array([[3.24146984, 3.5386362 , 4.10331056, 5.61426355],
       [3.4509173 , 4.82678741, 3.97105899, 3.30032048]])

In [8]:
#start,end,nomber of values
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [9]:
np.logspace(2,6,10)

array([1.00000000e+02, 2.78255940e+02, 7.74263683e+02, 2.15443469e+03,
       5.99484250e+03, 1.66810054e+04, 4.64158883e+04, 1.29154967e+05,
       3.59381366e+05, 1.00000000e+06])

### Slicing

In [73]:
array=np.arange(1,21,1)
array=array.reshape(5,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [53]:
#array[row_slicing]
array[2:3]

array([[ 9, 10, 11, 12]])

In [55]:
#array[row_slicing,column_slicing]
array[1:3,2:3]

array([[ 7],
       [11]])

In [58]:
#Position of an element
#array[row][column]
array[2][3]

12

In [65]:
#desired rows 1, and 3 and all column
array[[1,3],:]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [66]:
#desired columns 1 and 2 and all rows
array[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [74]:
#fetch the diagonal elements of an array
np.diag(array)

array([ 1,  6, 11, 16])

In [69]:
array=np.arange(4,10,1)
array

array([4, 5, 6, 7, 8, 9])

In [ ]:
#reverse an array
array[::-1]

In [71]:
#fetch odd positions elements in an array
array[::2]

array([4, 6, 8])

In [72]:
#fetch even positions elements in an array
array[1::2]

array([5, 7, 9])

### Sorting an array

In [84]:
array=np.random.randint(1,21,20)
array=array.reshape(5,4)
array

array([[ 8,  6, 15,  2],
       [18,  2, 11, 12],
       [ 5,  4, 17, 17],
       [ 1, 17, 19, 19],
       [12,  1, 14,  6]])

In [85]:
#sort column wise
np.sort(array,axis=1)

array([[ 2,  6,  8, 15],
       [ 2, 11, 12, 18],
       [ 4,  5, 17, 17],
       [ 1, 17, 19, 19],
       [ 1,  6, 12, 14]])

In [86]:
#sort row wise
np.sort(array,axis=0)

array([[ 1,  1, 11,  2],
       [ 5,  2, 14,  6],
       [ 8,  4, 15, 12],
       [12,  6, 17, 17],
       [18, 17, 19, 19]])

In [91]:
#display  the order of the numbers with their position from highest to lowest
array=np.random.randint(1,20,10)
print("original array",array)
print("array's chronological order from highest to lowest",array.argsort())

original array [16 12 11 17 17 13  5 13 13 17]
array's chronological order from highest to lowest [6 2 1 5 7 8 0 3 4 9]


In [98]:
#to reshape multidimentional array to single dimentional
array.ravel()

array([ 3,  8, 19,  2,  4, 14, 19,  2, 19,  3,  4, 18, 12,  8,  2, 12,  1,
       17, 12,  9])

In [99]:
array.flatten()

array([ 3,  8, 19,  2,  4, 14, 19,  2, 19,  3,  4, 18, 12,  8,  2, 12,  1,
       17, 12,  9])

In [101]:
#max element position
array.argmax()

2

### Fetch  array in for loop

In [92]:
array=np.random.randint(1,21,20)
array=array.reshape(5,4)
array

array([[ 3,  8, 19,  2],
       [ 4, 14, 19,  2],
       [19,  3,  4, 18],
       [12,  8,  2, 12],
       [ 1, 17, 12,  9]])

In [96]:
for row in array:
    print(row)

[ 3  8 19  2]
[ 4 14 19  2]
[19  3  4 18]
[12  8  2 12]
[ 1 17 12  9]


In [97]:
for column in array.T:
    print(column)

[ 3  4 19 12  1]
[ 8 14  3  8 17]
[19 19  4  2 12]
[ 2  2 18 12  9]


In [100]:
for element in array.ravel():
    print(element)

3
8
19
2
4
14
19
2
19
3
4
18
12
8
2
12
1
17
12
9


### Mathematical/statistical operations in an array

In [ ]:
#mean,std,median,percentile,corrcoeff,

### Applying functions on an array

In [ ]:
unique,uniquecount,vectorizer,isnan,any,all,change datatype,applyalong axis

### making insert,delete,split rowwise and colummn wise

In [ ]:
swap,join,merge,concat,update particular value

### Operation on two arrays

In [ ]:
np.where,corr,