In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
array=np.array([1,2,3,4,5,6])
len(array)

6

In [4]:
array=array.reshape(2,3)
array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
array.shape

(2, 3)

In [6]:
#start,end,gap
np.arange(2,7),np.arange(3,9,2)

(array([2, 3, 4, 5, 6]), array([3, 5, 7]))

In [7]:
array=np.arange(1,20,1)
array#.reshape(4,5)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.tile(4,(2,5))

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [11]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [12]:
#set random variable
np.random.seed(3)

In [13]:
#start,end,shape
np.random.randint(2,5,(2,3))

array([[4, 2, 3],
       [2, 2, 2]])

In [14]:
#limit from zero,shape
np.random.choice(10,(2,3))

array([[5, 3, 9],
       [9, 5, 7]])

### Float numbers

In [15]:
#0 to 1 values shape random
np.random.rand(2,3)

array([[0.0935515 , 0.69482365, 0.14537014],
       [0.4531723 , 0.21557701, 0.35390507]])

In [16]:
#start,end,array shape
np.random.uniform(2,6,(2,4))

array([[3.9705437 , 5.65320578, 5.06330551, 5.89459307],
       [3.60944257, 4.2110878 , 3.22544252, 4.34647988]])

In [17]:
#start,end,nomber of values
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [18]:
np.logspace(2,6,10)

array([1.00000000e+02, 2.78255940e+02, 7.74263683e+02, 2.15443469e+03,
       5.99484250e+03, 1.66810054e+04, 4.64158883e+04, 1.29154967e+05,
       3.59381366e+05, 1.00000000e+06])

### Slicing

In [19]:
array=np.arange(1,21,1)
array=array.reshape(5,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [20]:
#array[row_slicing]
array[2:3]

array([[ 9, 10, 11, 12]])

In [21]:
#array[row_slicing,column_slicing]
array[1:3,2:3]

array([[ 7],
       [11]])

In [22]:
#Position of an element
#array[row][column]
array[2][3]

12

In [23]:
#desired rows 1, and 3 and all column
array[[1,3],:]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

In [24]:
#desired columns 1 and 2 and all rows
array[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [25]:
#fetch the diagonal elements of an array
np.diag(array)

array([ 1,  6, 11, 16])

In [26]:
array=np.arange(4,10,1)
array

array([4, 5, 6, 7, 8, 9])

In [27]:
#reverse an array
array[::-1]

array([9, 8, 7, 6, 5, 4])

In [28]:
#fetch odd positions elements in an array
array[::2]

array([4, 6, 8])

In [29]:
#fetch even positions elements in an array
array[1::2]

array([5, 7, 9])

### Sorting an array

In [30]:
array=np.random.randint(1,21,20)
array=array.reshape(5,4)
array

array([[ 8, 12,  2, 16],
       [17,  6, 18, 15],
       [ 1,  1, 10, 19],
       [ 6,  8,  6, 15],
       [ 2, 18,  2, 11]])

In [31]:
#sort column wise
np.sort(array,axis=1)

array([[ 2,  8, 12, 16],
       [ 6, 15, 17, 18],
       [ 1,  1, 10, 19],
       [ 6,  6,  8, 15],
       [ 2,  2, 11, 18]])

In [32]:
#sort row wise
np.sort(array,axis=0)

array([[ 1,  1,  2, 11],
       [ 2,  6,  2, 15],
       [ 6,  8,  6, 15],
       [ 8, 12, 10, 16],
       [17, 18, 18, 19]])

In [33]:
#display  the order of the numbers with their position from highest to lowest
array=np.random.randint(1,20,10)
print("original array",array)
print("array's chronological order from highest to lowest",array.argsort())

original array [12  5  4 17 17  1 17 19 19 12]
array's chronological order from highest to lowest [5 2 1 0 9 3 4 6 7 8]


In [34]:
#to reshape multidimentional array to single dimentional
array.ravel()

array([12,  5,  4, 17, 17,  1, 17, 19, 19, 12])

In [35]:
array.flatten()

array([12,  5,  4, 17, 17,  1, 17, 19, 19, 12])

In [36]:
#max element position
array.argmax()

7

### Fetch  array in for loop

In [37]:
array=np.random.randint(1,21,20)
array=array.reshape(5,4)
array

array([[ 1, 14,  6, 17],
       [ 2, 18, 19,  3],
       [ 5,  9, 13, 17],
       [11, 17,  5, 18],
       [18,  9,  8,  1]])

In [38]:
for row in array:
    print(row)

[ 1 14  6 17]
[ 2 18 19  3]
[ 5  9 13 17]
[11 17  5 18]
[18  9  8  1]


In [39]:
for column in array.T:
    print(column)

[ 1  2  5 11 18]
[14 18  9 17  9]
[ 6 19 13  5  8]
[17  3 17 18  1]


In [40]:
for element in array.ravel():
    print(element)

1
14
6
17
2
18
19
3
5
9
13
17
11
17
5
18
18
9
8
1


### Mathematical/statistical operations in an array

In [57]:
array

array([[ 1, 14,  6, 17],
       [ 2, 18, 19,  3],
       [ 5,  9, 13, 17],
       [11, 17,  5, 18],
       [18,  9,  8,  1]])

In [48]:
array.mean(),array.std(),np.median(array,axis=0)

(array([ 9.5 , 10.5 , 11.  , 12.75,  9.  ]),
 6.272758563821822,
 array([ 5., 14.,  8., 17.]))

In [50]:
array.mean(axis=0),array.mean(axis=1)

(array([ 7.4, 13.4, 10.2, 11.2]), array([ 9.5 , 10.5 , 11.  , 12.75,  9.  ]))

In [58]:
np.percentile(array,q=[5,95])

array([ 1.  , 18.05])

In [61]:
#coerrelation between two features
np.corrcoef(array)

array([[ 1.        ,  0.09832195,  0.70490738,  0.75951873, -0.8674856 ],
       [ 0.09832195,  1.        ,  0.05579284, -0.34992476, -0.12906159],
       [ 0.70490738,  0.05579284,  1.        ,  0.19298026, -0.96230317],
       [ 0.75951873, -0.34992476,  0.19298026,  1.        , -0.39680665],
       [-0.8674856 , -0.12906159, -0.96230317, -0.39680665,  1.        ]])

### Applying functions on an array

In [ ]:
unique,uniquecount,vectorizer,isnan,any,all,change datatype,applyalong axis

In [62]:
#get unique elements
np.unique(array)

array([ 1,  2,  3,  5,  6,  8,  9, 11, 13, 14, 17, 18, 19])

In [66]:
#element count
np.unique(array,return_counts=True)
#array unique element and its count in the array

(array([ 1,  2,  3,  5,  6,  8,  9, 11, 13, 14, 17, 18, 19]),
 array([2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 3, 3, 1], dtype=int64))

In [81]:
#change datatype
array.astype('float')

array([[ 1., 14.,  6., 17.],
       [ 2., 18., 19.,  3.],
       [ 5.,  9., 13., 17.],
       [11., 17.,  5., 18.],
       [18.,  9.,  8.,  1.]])

In [88]:
np.apply_along_axis(func,arr=array,axis=0)

array([[11, 24, 16, 27],
       [12, 28, 29, 13],
       [15, 19, 23, 27],
       [21, 27, 15, 28],
       [28, 19, 18, 11]])

In [71]:
def func(a):
    return a+10
v=np.vectorize(func)
v(array)

array([[11, 24, 16, 27],
       [12, 28, 29, 13],
       [15, 19, 23, 27],
       [21, 27, 15, 28],
       [28, 19, 18, 11]])

In [80]:
for i in array:
    print(i.all())

True
True
True
True
True


In [64]:
#fetch null value
np.isnan(array)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### making insert,delete,split rowwise and colummn wise

In [ ]:
swap,join,merge,concat,update particular value

### Operation on two arrays

In [ ]:
np.where,corr,